services:
  db:
    image: postgres:15
    container_name: fixya_db
    restart: always
    environment:
      POSTGRES_DB: fixya_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - fixya_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./FixYa
      dockerfile: Dockerfile
    container_name: fixya_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fixya_db
    ports:
      - "8000:8000"
    volumes:
      - ./FixYa:/app

  frontend:
    build:
      context: ./fixya-frontend
      dockerfile: Dockerfile
    container_name: fixya_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./fixya-frontend:/app
      - /app/node_modules

volumes:
  fixya_postgres_data: